### ISSUE TITLE
Demo真机运行直接闪退

### ISSUE THREAD

**Issue by jianke123** [qhd/ANYMethodLog#1]
我看了之后觉得非常厉害，但是遗憾的是您提供的demo真机运行就闪退，我的手机是iphone7，系统是10.2.1，能否帮忙解决下问题，让我多膜拜学习，您可以加下留下QQ加个好友呢

**Comment by qhd** [comment]
是的，真机会有问题，不过我最近解决了，还没测试所以还没提交上来。我QQ：376503195

**Comment by jianke123** [comment]
👍赞！很期待您的更新
