### ISSUE TITLE
有办法打印某个类某个方法中的所有方法调用吗？

### ISSUE THREAD

**Issue by wonderffee** [qhd/ANYMethodLog#7]
RT，现在的情况是好像只能打印某个类的所有方法，或者某个类的某个方法的调用日志，如果我想指定特定类特定方法，打印这个特定方法里面的所有方法调用，有可行性吗？

**Comment by qhd** [comment]
目前还不行。目前打印基类 NSObject 的所有方法是会出错的，如果解决了这个问题就能实行你所说的。

**Comment by qhd** [comment]
按照目前，一个解决你问题的提议：如果你知道“这个特定方法”大概会使用哪些类，你可以同时监听多个类。

**Comment by wonderffee** [comment]
了解，同时监听是很自然的想法，就是略麻烦啊
感谢回复
